package transport

import (
	"fmt"
	"net/http"
	"strings"
)

// HostRule is one host a provider's model-call and app surface reach: either
// an exact hostname, or a suffix that also covers every subdomain under it.
type HostRule struct {
	Host              string
	IncludeSubdomains bool
}

// hostTable carries the API and app hosts each provider's model-call traffic
// and browser surface reach, keyed by provider rather than one shared list:
// every consumer below -- the intercept allowlist and the PAC body -- is
// built from the union of the rows of the providers a caller names
// (Config.Providers), never from the whole table.
//
// A host may appear in more than one row (api.meta.ai is in claude-code,
// muse and codex). Which provider owns a call on such a host is decided by
// CandidatesForHost plus a carrier check in the caller, never by row order.
// The muse row is inert until Muse has a session carrier: a call there
// resolves no provider and is skipped and counted.
//
// auth.* is excluded by construction: the table lists no bare
// "anthropic.com" or "openai.com", so nothing here ever widens to cover
// auth.anthropic.com, auth.openai.com or platform.openai.com. Do not add one.
var hostTable = map[string][]HostRule{
	"claude-code": {
		{Host: "api.anthropic.com"},
		{Host: "claude.ai", IncludeSubdomains: true},
		{Host: "api.meta.ai"},
	},
	"muse": {
		{Host: "api.meta.ai"},
	},
	"codex": {
		{Host: "api.openai.com"},
		{Host: "chatgpt.com", IncludeSubdomains: true},
		{Host: "api.meta.ai"},
	},
}

// RowsFor returns provider's rows, or nil for a provider the table does not
// name. The returned slice is a copy: a caller mutating it must not be able
// to widen what a later Union call returns.
func RowsFor(provider string) []HostRule {
	rows := hostTable[provider]
	if rows == nil {
		return nil
	}
	out := make([]HostRule, len(rows))
	copy(out, rows)
	return out
}

// Union is what the installed provider set intercepts: the deduplicated rows
// of every named provider, in the order the providers and their own rows are
// given, so PACBody's generated arms and a repeated call's output are stable.
// An unrecognized provider name contributes no rows rather than erroring,
// because a caller building this from a possibly-stale activation record
// must not fail an install over one lane's mistake.
func Union(providers ...string) []HostRule {
	seen := make(map[HostRule]bool)
	var out []HostRule
	for _, p := range providers {
		for _, r := range hostTable[p] {
			if seen[r] {
				continue
			}
			seen[r] = true
			out = append(out, r)
		}
	}
	return out
}

// AllowlistFor is the Config.Validate default: the intercept allowlist for
// the given providers' union.
func AllowlistFor(providers ...string) Allowlist {
	return NewAllowlistFromRules(Union(providers...)...)
}

// exactHostFor returns provider's one exact-match row, so DefaultInterceptHost
// stays derived from the table instead of a second, independently-maintained
// literal.
func exactHostFor(provider string) string {
	for _, r := range hostTable[provider] {
		if !r.IncludeSubdomains {
			return r.Host
		}
	}
	return ""
}

// hostTableProviders lists hostTable's own keys in a fixed order, most
// specific session carrier first (Claude Code's own header, then Muse's,
// then Codex's generic request id), so CandidatesForHost's answer (and any
// other caller enumerating the whole table) does not depend on Go's
// randomized map iteration. Named here rather than derived from
// provider.Supported(): this package's import guard (internal/depguard)
// allows no repo-local import beyond internal/gateway, so the provider names
// are written down directly, the same way hostTable's own map keys already
// are.
var hostTableProviders = []string{"claude-code", "muse", "codex"}

// CandidatesForHost lists every provider whose host-table rows cover host --
// exact match or a subdomain of a suffix row -- in hostTableProviders' order,
// or nil when none do. More than one is normal (api.meta.ai): the caller
// picks among them by session carrier and must skip, never guess, when zero
// or several resolve. It reuses the same Allowlist matching a relayed call
// itself passed through to reach the handler at all, rather than a second
// host-matching rule that could drift from it.
func CandidatesForHost(host string) []string {
	var out []string
	for _, name := range hostTableProviders {
		if NewAllowlistFromRules(RowsFor(name)...).Allows(host) {
			out = append(out, name)
		}
	}
	return out
}

// pacBanner marks the body as generated; a hand edit would be silently
// overwritten the next time the union changes.
const pacBanner = "// Generated by openbox from the installed provider host table. Do not edit.\n"

// PACBody is the proxy auto-config script for the given providers' union: a
// host in the union routes through proxyAddr with a DIRECT fallback --
// a stopped relay lets that traffic through uninspected, which is the
// deliberate exposure `doctor` reports -- and every other host goes DIRECT
// outright. addr is the relay's own configured address, never a hardcoded
// default: a PAC generated for one relay must not silently point a browser
// at another one's port.
func PACBody(proxyAddr string, providers ...string) string {
	var b strings.Builder
	b.WriteString(pacBanner)
	b.WriteString("function FindProxyForURL(url, host) {\n")
	b.WriteString("  host = host.toLowerCase();\n")
	for _, r := range Union(providers...) {
		host := asciiLower(r.Host)
		if r.IncludeSubdomains {
			fmt.Fprintf(&b, "  if (host === %q || dnsDomainIs(host, %q)) return %q;\n",
				host, "."+host, "PROXY "+proxyAddr+"; DIRECT")
		} else {
			fmt.Fprintf(&b, "  if (host === %q) return %q;\n", host, "PROXY "+proxyAddr+"; DIRECT")
		}
	}
	b.WriteString("  return \"DIRECT\";\n")
	b.WriteString("}\n")
	return b.String()
}

// pacContentType is the MIME type browsers and OS proxy configuration expect
// for a proxy auto-config script; serving anything else is silently ignored
// by some clients rather than rejected.
const pacContentType = "application/x-ns-proxy-autoconfig"

// pacHandler answers GET and HEAD on /proxy.pac with the generated body and
// 404s every other path or method, including POST /proxy.pac: this endpoint
// only ever reports the union already visible in the install report, and
// never accepts input. It is wired as the goproxy engine's NonproxyHandler
// (identity.go), which only ever sees a non-absolute-URI request -- so this
// adds no port, no goroutine and never touches the CONNECT path a relayed
// call takes.
func pacHandler(proxyAddr string, providers []string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/proxy.pac" || (r.Method != http.MethodGet && r.Method != http.MethodHead) {
			http.NotFound(w, r)
			return
		}
		body := PACBody(proxyAddr, providers...)
		w.Header().Set("Content-Type", pacContentType)
		w.Header().Set("Cache-Control", "no-store")
		if r.Method == http.MethodHead {
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(body)))
			return
		}
		_, _ = w.Write([]byte(body))
	})
}
